In [27]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def combine_features(row):
    features = ["Actors","Genre","Director"]
    return " ".join(row[features])
def get_title_from_index(index):
    return df[df.index == index]["Drama_Name"].values[0]
def get_index_from_title(title):
    return df[df.Drama_Name == title]["index"].values[0]

df = pd.read_csv("./data/kdrama_contentbased.csv")
df['index']  = [i for i in range(len(df))]
df["combined_features"] = df.apply(combine_features,axis=1) #applying combined_features() method over each rows of dataframe and storing the combined string in "combined_features" column

cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
cosine_sim = cosine_similarity(count_matrix)
print(cosine_sim)


[[1.         0.3354102  0.38575837 ... 0.07216878 0.21759707 0.25515518]
 [0.3354102  1.         0.3105295  ... 0.19364917 0.23354968 0.18257419]
 [0.38575837 0.3105295  1.         ... 0.17817416 0.34918995 0.22047928]
 ...
 [0.07216878 0.19364917 0.17817416 ... 1.         0.05025189 0.05892557]
 [0.21759707 0.23354968 0.34918995 ... 0.05025189 1.         0.10660036]
 [0.25515518 0.18257419 0.22047928 ... 0.05892557 0.10660036 1.        ]]


In [28]:
movie_user_likes = "The Heirs"

movie_index = get_index_from_title(movie_user_likes)
similar_movies = list(enumerate(cosine_sim[movie_index])) #accessing the row corresponding to given movie to find all the 
# print((similar_movies))

sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[1:6]
print("Top 5 similar movies to "+movie_user_likes+" are:\n")
for element in sorted_similar_movies:
    print(get_title_from_index(element[0]))


Top 5 similar movies to The Heirs are:

About time
My girlfriend is gumiho
Encounter
Doctors
Pinocchio


In [29]:
import pickle
pickle.dump(df,open('movie_list.pkl','wb'))
pickle.dump(cosine_sim,open('similarity.pkl','wb'))

In [15]:
from bing_image_downloader import downloader

downloader.download("Angel’s last mission Love", limit=1, output_dir='image', \
        adult_filter_off=True, force_replace=False, timeout=60, verbose=True)


[%] Downloading Images to /Users/wkarlina/Documents/GATECH/git/recommendation-engine/image/Angel’s last mission Love


[!!]Indexing page: 1

[%] Indexed 1 Images on Page 1.


[%] Downloading Image #1 from https://image.tmdb.org/t/p/original/384Rq41XJTQbiCreE6806id44QC.jpg
[%] File Downloaded !



[%] Done. Downloaded 1 images.

Please show your support here
https://www.buymeacoffee.com/gurugaurav


